export const mantenimientoRoutes = {
  CLIENTE: "cliente",
  PROVEEDOR: "proveedor",
  VENDEDOR: "vendedor",
  PERSONAL: "personal",
  CORRELATIVO: "correlativo",
  TRANSPORTISTA: "transportista",
  MEDICO: "medico",
  USUARIO: "usuario",

  ALMACEN: "almacen",
  LINEA: "linea",
  SUBLINEA: "sublinea",
  MARCA: "marca",
  UNIDADESMEDIDA: "unidadesmedida",
  ENTIDADESBANCARIAS: "entidadesBancarias",
  CUENTASCORRIENTES: "cuentasCorrientes",
  VEHICULOS: "vehiculos",
  TRANSPORTISTAS: "transportistas",
  DEPARTAMENTO: "departamento",
  PROVINCIA: "provincia",
  DISTRITO: "distrito",
  TIPOPAGO: "tipopago",
  TIPOPRODUCTO: "tipoproducto",
  TIPOVENTA: "tipoventa",

  ARTICULO: "articulo",
  MOVIMIENTOARTICULO: "movimientoArticulo",
  CUADRESTOCK: "cuadreStock",
  CUADRESTOCK_FORMULARIO: "cuadreStock/form",
  FARMACOLOGIA: "farmacologia",
  GRUPOFARMACOLOGICO: "grupofarmacologico",
  PRESENTACIONGENERAL: "presentationgeneral",
  PRECIOMAYORISTA: "preciomayorista",
  LOTE: "lote",
  CONFIGURACIONLOTE: "configuracionlote",

  TIPOCAMBIO: "tipocambio",
  ENTIDADBANCARIA: "entidadbancaria",
  CUENTABANCARIA: "cuentabancaria",
};
